### ISSUE TITLE
OpenCV 3.0

### ISSUE THREAD

**Issue by sath33sh** [muesli/smartcrop#15]
I'm getting the following error with OpenCV 3.0 installed. Just curious whether smartcrop is known to work with OpenCV 3.0. If not which version is safer to use?

0.625
original resolution: 960x640
scale: 1.000000, cropw: 400.000000, croph: 400.000000, minscale: 1.000000
Time elapsed edge: 87.613185ms
OpenCV Error: Unspecified error (The node does not represent a user object (unknown type?)) in cvRead, file /home/admin/source/opencv/opencv-3.0.0/modules/core/src/persistence.cpp, line 4976
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/admin/source/opencv/opencv-3.0.0/modules/core/src/persistence.cpp:4976: error: (-2) The node does not represent a user object (unknown type?) in function cvRead

SIGABRT: abort
PC=0x7f7a6c6f7165
signal arrived during cgo execution

goroutine 15 [syscall, locked to thread]:
runtime.cgocall_errno(0x40c230, 0xc2081aae40, 0x0)
    /usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc2081aae20 sp=0xc2081aadf8
github.com/lazywei/go-opencv/opencv._Cfunc_cvLoadHaarClassifierCascade(0x223d540, 0x100000001, 0x0)
    /home/admin/go/src/github.com/lazywei/go-opencv/opencv/:677 +0x44 fp=0xc2081aae40 sp=0xc2081aae20
github.com/lazywei/go-opencv/opencv.LoadHaarClassifierCascade(0xbcb430, 0x3e, 0x7f7a72ca8ac0)
    /home/admin/go/src/github.com/lazywei/go-opencv/opencv/cvaux.go:61 +0x90 fp=0xc2081aae78 sp=0xc2081aae40
github.com/muesli/smartcrop.faceDetect(0xc20819c3e0, 0xc2089ad180)
    /home/admin/go/src/github.com/muesli/smartcrop/crop.go:420 +0x173 fp=0xc2081ab088 sp=0xc2081aae78
github.com/muesli/smartcrop.analyse(0xc20819c3e0, 0x4079000000000000, 0x4079000000000000, 0x3ff0000000000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/admin/go/src/github.com/muesli/smartcrop/crop.go:284 +0x31e fp=0xc2081ab2d8 sp=0xc2081ab088
github.com/muesli/smartcrop.SmartCrop(0xc20819d940, 0x280, 0x280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)

**Comment by muesli** [comment]
Personally I use opencv 2.4.5, but I'll check out how it behaves with version 3, soon. It looks like it might just fail loading your cascade xml?

**Comment by kaikuehne** [comment]
Hi. I get a similar error when loading the xml file (none of the included xml files work). I'm using opencv 2.4.5. Can you tell what I might try to fix this? Thanks

**Comment by muesli** [comment]
We've dropped face-detection & the opencv dependency for the time being. I'll add a new FaceAnalyzer in the next days, but by the looks it will depend on opencv2 still. Thanks for reporting the issue upstream.
